import { BlogBuilder } from "../../components/blog/BlogBuilder";

export default new BlogBuilder({
  id: "nuclear-renewable-complementary",
  title:
    "The Power of Complementary Roles: Why Nuclear and Renewables Should Work Together",
  cover: require("../../assets/blog/nuclear-renewable-complementary/nuclear-renewable-both-button.png"),
  publishedDate: "2023-04-05",
  description: (
    <>
      Pursuing a green future with high energy needs is a global challenge
      today. There is no doubt that fossil fuels, the primary source of
      generating electricity, must come to an end. However, should nuclear or
      renewable energy be the alternative?
    </>
  ),
})
  .addParagraph(
    <>
      When I was pursuing my bachelor's degree, the students often had this
      discussion about nuclear power plants. Are we really need nuclear for
      clean energy? Isn't that what renewable energies are for? For a long time,
      I have always been on the nuclear side thinking that these energies are
      something to be compared against. Then, sometime on a regular lecture day,
      my professor said{" "}
      <i>"Why nuclear OR renewable? Why not nuclear AND renewable?"</i> I was
      like, yes of course!
    </>
  )
  .addImage({
    image: require("../../assets/blog/nuclear-renewable-complementary/sttn-batan-instagram.jpg"),
    caption:
      "STTN-BATAN n.k.a. Poltek Nuklir, where I spent 4 years studying engineering",
  })
  .addParagraph(
    <>
      Electricity generated by fossil fuels is the second largest contributor to
      global carbon emissions (after transportation) and has the highest death
      rates per electricity produced compared to other energy sources. Fossil
      fuels are also the largest source of electricity now, if we currently
      cannot massively replace fossil fuel transportation, somehow the world has
      to consider energy alternatives to generate electricity.
    </>
  )
  .addImage({
    image: require("../../assets/blog/nuclear-renewable-complementary/death-rates-from-energy-production-per-twh.png"),
    caption: (
      <>
        Mortality rate per unit of electricity produced, from{" "}
        <a href="https://ourworldindata.org/grapher/death-rates-from-energy-production-per-twh">
          ourworldindata.org
        </a>
      </>
    ),
  })
  .addParagraph(
    <>
      By energy alternatives, I mean a cleaner source for a greener future. And
      many countries are turning to renewable energy sources such as solar,
      wind, and hydropower to power their grids. While renewable energy is
      essential in reducing carbon emissions, it alone cannot replace the
      baseload power provided by fossil energy for its low efficiency and
      time-based availability. Therefore, it is crucial to recognize the
      importance of nuclear energy as a complementary source of power that can
      work in tandem with renewables.
    </>
  )

  .addImage({
    image: require("../../assets/blog/nuclear-renewable-complementary/nicolas-hippert-C82jAEQkfE0-unsplash.jpg"),
    //   caption: "Doel nuclear power station in Belgium by Nicolas Hippert",
    caption: (
      <>
        Doel nuclear power station in Belgium by{" "}
        <a href="https://unsplash.com/fr/@nhippert?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">
          Nicolas Hippert
        </a>{" "}
        on{" "}
        <a href="https://unsplash.com/photos/C82jAEQkfE0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">
          Unsplash
        </a>
      </>
    ),
  })
  .addParagraph(
    <>
      The use of renewable energy sources has been gaining momentum in recent
      years due to the depletion of fossil fuel resources and the concerns about
      its impact. Unlike intermittent output of renewables, nuclear power plants
      are capable of generating large amounts of power continuously regardless
      of weather conditions or time of day. This reliability makes nuclear
      energy an important factor to be considered as the most ideal source of
      baseload power.
    </>
  )
  .addImage({
    image: require("../../assets/blog/nuclear-renewable-complementary/mark-konig-WIxAt-XyXO0-unsplash.jpg"),
    // caption: "Wind turbines in Germany by Mark König",
    caption: (
      <>
        Wind turbines in Germany by{" "}
        <a href="https://unsplash.com/@markkoenig?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">
          Mark König
        </a>{" "}
        on{" "}
        <a href="https://unsplash.com/photos/WIxAt-XyXO0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">
          Unsplash
        </a>
      </>
    ),
  })
  .addParagraph(
    <>
      Combining the two can provide a sustainable future that meets modern
      society's energy demands while protecting our planet for future
      generations. The strengths of both nuclear and renewables can be harnessed
      to provide a reliable and sustainable energy supply. Nuclear energy offers
      a consistent and reliable source of power, while renewable energy sources
      can help to reduce carbon emissions and provide energy during times of
      high demand.
    </>
  );
